### PR TITLE
Properly handle multiple rename (delete) events in inotify buffer

### LINKED ISSUE #171: Error when deleting large number of files
This is a linux-only problem. Here's how to reproduce:

1. Run the following nodejs program on Linux (Ubuntu latest LTS is my platform) 
```javascript
const nsfw = require('nsfw');

console.log(`watching ${process.argv[2]`}`);

const watch= nsfw(process.argv[2], events => {
   console.log('got events');
   event.forEach(element => {
      console.log(JSON.stringify({...element}));
}, {
   errorCallback: err => {
      console.error(err);
   }
}).then(instance => {
   instance.start();
   console.log('watch started');
});
```

the program expects as a paremeter with a large (> 1000) number of directories. A `node_modules` folder of a complex project makes for good test data.

2. In the Ubuntu "Files" file explorer, select all subdirectories of the dir you passed as a paramenter in 1. and hit the delete button
3. Observe: after a while, you get an error message in the console:
```
Error: Service shutdown: root path changed (rename or deleted) 
```

### PR DESCRIPTION
**Pull request by tsmaeder**
Supposed to fix #171 

Contributed on behalf of ST Microelectronics

Signed-off-by: Thomas Mäder <t.s.maeder@gmail.com>

### CODE REVIEW

**Comment by tsmaeder** [comment]
@julianmesa-gitkraken what's the protocol for getting PR's merged?

**Comment by julianmesa-gitkraken** [comment]
> @julianmesa-gitkraken what's the protocol for getting PR's merged?

I need to reproduce and test it, I will try to do it today

**Comment by tsmaeder** [comment]
Fantastic, thanks.

**Review by julianmesa-gitkraken — APPROVED** [review]
After testing, I agree with the solution.
We are moving to trash and `removeDirectory` should be called when `isDirectoryRemoval` only.

**Comment by ianhattendorf** [comment]
Thanks!

**Comment by tsmaeder** [comment]
@ianhattendorf can you give an ETA when a new release will go out?

**Pull request merged**
