### PR TITLE
Use individual lodash function modules

### LINKED ISSUE #22: Consider shipping individual lodash modules to reduce lib size
The full version of `lodash` takes 4.9mb uncompressed but nsfw is only using `isInteger` and `isUndefined`. It would be better to ship the individual modules, eg. https://www.npmjs.com/package/lodash.isinteger

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #22 

---

This change reduces the size of node_modules that would need to be shipped by almost 5mb.

Tests failed locally, not sure if I have the right setup or if they're flaky?

### CODE REVIEW

**Comment by implausible** [comment]
Seems appropriate. File watching tests occasionally experience timeouts.

**Comment by implausible** [comment]
Any output regarding the local test failures?

**Comment by Tyriar** [comment]
@implausible I ran them again and they all passed :+1: 

```
$ npm test
...
Finished in 86.444 seconds
11 Tests, 0 Failures, 0 Skipped
```

**Comment by Tyriar** [comment]
@implausible any chance we could get a patch release to include this?

**Comment by implausible** [comment]
I have a patch release heading out the door tomorrow.

**Comment by implausible** [comment]
@Tyriar Patch is out.

**Comment by Tyriar** [comment]
Thanks @implausible 👍

**Pull request merged**
