### PR TITLE
Update ci and packages

### PR DESCRIPTION
**Pull request by julianmesa-gitkraken**
Update CI
Update packages
Fix building in path with spaces

### CODE REVIEW

**Review by ianhattendorf — APPROVED** [review]

**Comment by jrk94** [comment]
@julianmesa-gitkraken when can we expect a release with this fix?

**Comment by ianhattendorf** [comment]
> @julianmesa-gitkraken when can we expect a release with this fix?

Shortly, I plan on releasing this week when I have some free time.

**Comment by rmmoreira84** [comment]
Thank you @julianmesa-gitkraken

**Comment by ianhattendorf** [comment]
@jrk94 @rmmoreira84 nsfw@2.2.5 has been published.

**Pull request merged**
